/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 SockModel.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SockModel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh005_3.geometry} material={materials.Cuff} />
      <mesh geometry={nodes.mesh005.geometry} material={materials.Sock_Texture} />
      <mesh geometry={nodes.mesh005_1.geometry} material={materials.Heel} />
      <mesh geometry={nodes.mesh005_2.geometry} material={materials.Toe} />
    </group>
  )
}

useGLTF.preload('/SockModel.gltf')
